page_number=0;
function left_arrow()
{
if(page_number!=0){
page_number=page_number-1;
console.log(page_number);
}else{
page_number=19;
console.log(page_number);
}
draw()
}

function right_arrow()
{
if(page_number!=19){
page_number=page_number+1;
console.log(page_number);
}else{
page_number=0;
console.log(page_number);
}
draw()
}
function draw()
{
if(page_number==0){
document.getElementById("menu_img").innerHTML="Page1.png";
}
if(page_number==1){
document.getElementById("menu_img").innerHTML="Page2.png";
}
if(page_number==2){
document.getElementById("menu_img").innerHTML="Page3.png";
}
if(page_number==3){
document.getElementById("menu_img").innerHTML="Page4.png";
}
if(page_number==4){
document.getElementById("menu_img").innerHTML="Page5.png";
}
if(page_number==5){
document.getElementById("menu_img").innerHTML="Page6.png";
}
if(page_number==6){
document.getElementById("menu_img").innerHTML="Page7.png";
}
if(page_number==7){
document.getElementById("menu_img").innerHTML="Page8.png";
}
if(page_number==8){
document.getElementById("menu_img").innerHTML="Page9.png";
}
if(page_number==9){
document.getElementById("menu_img").innerHTML="Page10.png";
}
if(page_number==10){
document.getElementById("menu_img").innerHTML="Page11.png";
}
if(page_number==11){
document.getElementById("menu_img").innerHTML="Page12.png";
}
if(page_number==12){
document.getElementById("menu_img").innerHTML="Page13.png";
}
if(page_number==13){
document.getElementById("menu_img").innerHTML="Page14.png";
}
if(page_number==14){
document.getElementById("menu_img").innerHTML="Page15.png";
}
if(page_number==15){
document.getElementById("menu_img").innerHTML="Page16.png";
}
if(page_number==16){
document.getElementById("menu_img").innerHTML="Page17.png";
}
if(page_number==17){
document.getElementById("menu_img").innerHTML="Page18.png";
}
if(page_number==18){
document.getElementById("menu_img").innerHTML="Page19.png";
}
if(page_number==19){
document.getElementById("menu_img").innerHTML="Page20.png";
}
}
draw()